-- drop table
drop table T_CUSTOMER if exists;

-- create table
create table T_CUSTOMER (
  ID          identity generated by default as identity (start with 1, increment by 1) not null,
  FIRST_NAME  varchar(100) not null,
  LAST_NAME   varchar(100) not null
);

-- add comments to the table
comment on table T_CUSTOMER is '客户表 ';
-- add comments to the columns
comment on column T_CUSTOMER.ID is 'id';
comment on column T_CUSTOMER.FIRST_NAME is '名';
comment on column T_CUSTOMER.LAST_NAME is '姓';
